<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="widget block block-static-block">
	
    <?php echo $block->getText(); ?>

	<div class="as-seen-on">
		<span>As Seen On:</span>
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/home/aso1.png" alt="" />
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/home/aso2.png" alt="" />
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/home/aso3.png" alt="" />
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/home/aso4.png" alt="" />
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/home/aso5.png" alt="" />
	</div>

	<div class="how-it-works">

	<?= $this->getChildHtml('three-simple-steps'); ?>

	<?= $this->getChildHtml('got-a-beard'); ?>

	</div>

	<?= $this->getChildHtml('how-it-works'); ?>

	<?= $this->getChildHtml('eleanorsoft.ingredients'); ?>

	<?= $this->getChildHtml('eleanorsoft.ourpromise'); ?>

	<?= $this->getChildHtml('atak.videoblocks'); ?>

	<?php print $this->getChildHtml('homepage.praise'); ?>

	<div class="container-fluid home-warning">*Specific results are not guaranteed. Actual results may vary.</div>

	<?php print $this->getChildHtml('homepage.testimonials'); ?>
	<?php //include "testimonials.php"; ?>

	<div class="container-fluid container-home-friend">
		<div class="home-friend">
			<div class="content">
				<h2 class="title">Refer a Friend</h2>
				<div class="subtitle">GET $25 OFF</div>
				<a href="#" class="action secondary">CLICK HERE</a>
			</div>
		</div>
	</div>

	<?= $this->getChildHtml('mens-grooming-manual'); ?>

	<?= $this->getChildHtml('the-summit-story'); ?>

	<?= $this->getChildHtml('what-makes-our-products-even-more-special'); ?>

	<?= $this->getChildHtml('shop-our-award-winners'); ?>

	<?= $this->getChildHtml('join-our-instagram-community'); ?>

</div>