<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Imindstudio\Autoship\Block\Orders $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
	<div class="table-wrapper orders-history">
		<table class="data table table-order-items history" id="my-orders-table">
			<caption class="table-caption"><?= __('Orders'); ?></caption>
			<thead>
			<tr>
				<th class="col id">
					<?= $block->escapeHtml(__('Next Sheep Date')); ?> /<br> <?= $block->escapeHtml(__('Frequency')); ?>
				</th>
				<th class="col id"><?= $block->escapeHtml(__('Order #')); ?></th>
				<?= $block->getChildHtml('extra.column.header'); ?>
				<th class="col shipping"><?= __('Ship To'); ?></th>
				<th class="col total"><?= __('Total'); ?></th>
				<th class="col status"><?= __('Status'); ?></th>
				<th class="col actions"><?= __('Edit Subscription'); ?></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($_orders as $_order): ?>
				<tr>
					<?php $nextShipDate = $_order->getNextShipDate(); ?>
					<td class="col id">
						<?= $nextShipDate ? $block->formatDate($nextShipDate) : __('Pending'); ?> /
						<br> <?= $_order->getFrequency(); ?>
					</td>
					<td class="col id"><?= $_order->getRealOrderId(); ?></td>
					<?php $extra = $block->getChildBlock('extra.container'); ?>
					<?php if ($extra): ?>
						<?php $extra->setOrder($_order); ?>
						<?= $extra->getChildHtml(); ?>
					<?php endif; ?>
					<td class="col shipping">
						<?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?>
					</td>
					<td class="col total"><strong><?=$_order->formatPrice($_order->getGrandTotal()); ?></strong></td>
					<td class="col status"><?= $_order->getStatusLabel(); ?></td>
					<td class="col actions">
						<a href="<?= $block->getUrl('aw_sarp/profile/view').'profile_id/'.$_order->getProfileId(); ?>" class="view">
							<span><?= __('Change the plan'); ?></span>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<?php if ($block->getPagerHtml()): ?>
		<div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
	<?php endif ?>
<?php else: ?>
	<div class="empty-orders-history">
		<p><?= __('You haven’t placed any orders yet.'); ?></p>
		<p><a href="<?php $block->getUrl('shop.html') ?>" class="action secondary">Shop Now</a></p>
		<p><img src="<?= $block->getViewFileUrl('images/lighthouse.png'); ?>" alt=""></p>
	</div>
<?php endif ?>