<div class="customer-reviews">
	
	<div class="pending-reviews">
		<div class="item">
			<div class="product-info">
				<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product-1.png" alt="" class="product-image" />
				<div class="product-name">Repair Serum for Men (30ml)</div>
				<p class="purchased">Purchased on: 06/27/2017</p>
				<p class="points">250 Reward Points</p>
			</div>
			<div class="pending-form">
				<form action="" method="post">
					<div class="fieldset">
						<div class="field">
							<div class="control">
								<textarea class="input-text" placeholder="Write Something..." rows="8"></textarea>
							</div>
						</div>
					</div>
					<button class="action primary" type="submit">
						<span>SUBMIT REVIEW</span>
					</button>
				</form>
			</div>
		</div>
		<div class="item">
			<div class="product-info">
				<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product-2.png" alt="" class="product-image" />
				<div class="product-name">Sample - Summit Moisturiser for Men</div>
				<p class="purchased">Purchased on: 06/27/2017</p>
				<p class="points">250 Reward Points</p>
			</div>
			<div class="pending-form">
				<form action="" method="post">
					<div class="fieldset">
						<div class="field">
							<div class="control">
								<textarea class="input-text" placeholder="Write Something..." rows="8"></textarea>
							</div>
						</div>
					</div>
					<button class="action primary" type="submit">
						<span>SUBMIT REVIEW</span>
					</button>
				</form>
			</div>
		</div>
	</div>
	
	<div class="pending-reviews-toolbar">
		<a href="/sales/order/history/" class="action primary">BACK TO ORDERS</a>
	</div>
	
</div>