<?php $balancePoints = $block->escapeHtml($block->getBalancePoints()); ?>
<div class="customer-rewards">
	<div id="rewards-accordion" class="accordion rewards-accordion">
		
		<div data-role="collapsible" class="accordion-title">
			<span class="title">REWARD BALANCE: <strong><?= $balancePoints; ?> POINTS</strong></span>
			<a href="javascript:;" class="trigger" data-role="trigger"><span>Details</span> <i class="icon-minus"></i><i class="icon-plus"></i></a>
		</div>
		<div data-role="content" class="accordion-content">
			<table class="data table reward-balance-table">
				<tbody>
				<tr>
					<th>Account Created</th>
					<td><?= $block->isLoggedIn() ? $block->escapeHtml($block->getSignUpPoints()) : '0' ?></td>
					<td class="info"></td>
				</tr>
				<tr>
					<th>Refer a Friend</th>
					<td><?= $block->escapeHtml($block->getReferredCustomerPoints()); ?></td>
					<td class="info"><a href="">Refer a Friend</a> now and earn reward points</td>
				</tr>
				<tr>
					<th>Reviews</th>
					<td><?= $block->escapeHtml($block->getCustomerReviewPoints()); ?></td>
					<td class="info"><a href="">Review</a> your recent purchases here</td>
				</tr>
				<tr>
					<th>Purchases</th>
					<td><?= $block->escapeHtml($block->getCustomerOrderPoints()); ?></td>
					<td class="info"><a href="/shop.html">Shop Now</a></td>
				</tr>
				<tr>
					<th>Points Redeemed</th>
					<td><?= $block->escapeHtml($block->getRedeemedPoints()); ?></td>
					<td class="info"></td>
				</tr>
				</tbody>
				<tfoot>
				<tr>
					<th>Balance</th>
					<td colspan="2"><?= $balancePoints; ?> points</td>
				</tr>
				</tfoot>
			</table>
		</div>
		
		<div data-role="collapsible" class="accordion-title">
			<span class="title">EARN MORE</span>
			<a href="javascript:;" class="trigger" data-role="trigger"><span>See How</span> <i class="icon-minus"></i><i class="icon-plus"></i></a>
		</div>
		<div data-role="content" class="accordion-content">
			<table class="data table reward-earn-table">
				<tbody>
				<tr>
					<th><span class="checkmark <?= $balancePoints != '0' ? 'checked' : ''; ?>"><i class="icon-ok"></i></span> Create an Account</th>
					<td class="info"><strong>+ 500</strong></td>
				</tr>
				<tr>
					<th><span class="checkmark"><i class="icon-ok"></i></span> Refer a Friend</th>
					<td class="info"><strong>+ 2500</strong> for every <a href="">new referral</a> that successfully completes a first time purchase.</td>
				</tr>
				<tr>
					<th><span class="checkmark <?= $block->escapeHtml($block->getCompletedOrdersCount()) != '0' ? 'checked' : ''; ?>"><i class="icon-ok"></i></span> Make a Purchases</th>
					<td class="info"><strong>+ 1</strong> point for every $1 spent. <a href="/shop.html">Shop Now</a></td>
				</tr>
				<tr>
					<th><span class="checkmark <?= $block->escapeHtml($block->getCustomerReviewPoints()) != '0' ? 'checked' : ''; ?>"><i class="icon-ok"></i></span> Reviews</th>
					<td class="info"><strong>+ 50</strong> for every product <a href="<?= $block->getUrl('sales/order/history'); ?>">review</a>.</td>
				</tr>
				</tbody>
			</table>
		</div>
		
		<?php /*
		<div data-role="collapsible" class="accordion-title">
			<span class="title">USE POINTS</span>
			<a href="javascript:;" class="trigger" data-role="trigger"><span>Details</span> <i class="icon-minus"></i><i class="icon-plus"></i></a>
		</div>
		<div data-role="content" class="accordion-content">
			<ul class="awards-use-points">
				<li>
					<div class="title">$5 Off</div>
					<p>500 points</p>
					<p>Discount Code (Apply on Checkout): <strong class="code">54EGR98</strong></p>
					<a href="javascript:;" class="copy">Copy to Clipboard</a>
				</li>
				<li>
					<div class="title">$10 Off</div>
					<p>1000 points</p>
					<p>Discount Code (Apply on Checkout): <strong class="code">DA6989B</strong></p>
					<a href="javascript:;" class="copy">Copy to Clipboard</a>
				</li>
				<li>
					<div class="title">$15 Off</div>
					<p>1500 points</p>
					<p>Discount Code (Apply on Checkout): <strong class="code">PR8587Q</strong></p>
					<a href="javascript:;" class="copy">Copy to Clipboard</a>
				</li>
			</ul>
		</div>
		*/ ?>
		
	</div>
</div>

<script>
	require(
		['jquery', 'accordion'],
		function ($) {
			$("#rewards-accordion").accordion();
			
			$('.awards-use-points .copy').click(function () {
				var text = $(this).parent().find('.code').text();
				copyToClipboard(text);
			});
		}
	);
	
	function copyToClipboard(text) {
		var aux = document.createElement("input");
		aux.setAttribute("value", text);
		document.body.appendChild(aux);
		aux.select();
		document.execCommand("copy");
		document.body.removeChild(aux);
	}
	
</script>