<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/* @var $block \Aheadworks\Sarp\Block\Customer\Subscription\Info\Orders\Pager */
// @codingStandardsIgnoreFile
?>
<?php if ($block->getItemsCount()): ?>
    <?php if ($block->getLastPageNum()>1): ?>
    <div class="pages">
        <ul class="items pages-items">
            <?php if (!$block->isFirstPage()): ?>
            <li class="item pages-item-previous">
                <a class="action previous" href="<?php echo $block->escapeUrl($block->getPreviousPageUrl()) ?>" title="<?php echo $block->escapeHtml(__('Previous')) ?>">
                    <span><?php echo $block->escapeHtml(__('Previous')) ?></span>
                </a>
            </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?php echo $block->escapeUrl($block->getFirstPageUrl()) ?>">
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php echo $block->escapeUrl($block->getPreviousJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $page): ?>
                <?php if ($block->isPageCurrent($page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span><?php /* @noEscape */ echo $page ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php echo $block->escapeUrl($block->getPageUrl($page)) ?>" class="page">
                            <span><?php /* @noEscape */ echo $page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php echo $block->escapeUrl($block->getNextJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
                <li class="item">
                    <a class="page last" href="<?php echo $block->escapeUrl($block->getLastPageUrl()) ?>">
                        <span><?php /* @noEscape */ echo $block->getLastPageNum() ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()): ?>
            <li class="item pages-item-next">
                <a class="action next" href="<?php echo $block->escapeUrl($block->getNextPageUrl()) ?>" title="<?php echo $block->escapeHtml(__('Next')) ?>">
                    <span><?php echo $block->escapeHtml(__('Next')) ?></span>
                </a>
            </li>
            <?php endif;?>
        </ul>
    </div>
    <?php endif; ?>
<?php endif ?>
