<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <?php /* <div class="block-title">
        <strong><?php echo __('Order Information') ?></strong>
    </div> */ ?>
    <div class="block-content">
	    
	    <div class="col col-address">
	    
	        <div class="box-order-billing">
			    <div class="box box-order-billing-address">
		            <strong class="box-title">
		                <span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
		            </strong>
		            <div class="box-content">
		                <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
		            </div>
		        </div>
		        <div class="box box-order-billing-method">
		            <strong class="box-title">
		                <span><?php /* @escapeNotVerified */ echo __('Payment Method') ?></span>
		            </strong>
		            <div class="box-content">
		                <?php echo $block->getPaymentInfoHtml() ?>
		            </div>
		        </div>
	        </div>
		
		    <?php if (!$_order->getIsVirtual()): ?>
			    <div class="box-order-shiiping">
				    <div class="box box-order-shipping-address">
					    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span></strong>
					    <div class="box-content">
						    <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
					    </div>
				    </div>
				
				    <div class="box box-order-shipping-method">
					    <strong class="box-title">
						    <span><?php /* @escapeNotVerified */ echo __('Shipping Method') ?></span>
					    </strong>
					    <div class="box-content">
						    <?php if ($_order->getShippingDescription()): ?>
							    <?php echo $block->escapeHtml($_order->getShippingDescription()) ?>
						    <?php else: ?>
							    <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
						    <?php endif; ?>
					    </div>
				    </div>
			    </div>
		    <?php endif; ?>
	    </div>
	    <div class="col col-review">
		    <div class="order-review">
			    <div class="title">FULFILMENT STATUS: FULFILLED</div>
			    <p>Review this order and earn reward points</p>
			    
			    <a href="<?php echo $block->getUrl() ?>autoship/customer/index/" class="action secondary">WRITE A REVIEW</a>
		    </div>
	    </div>
    </div>
</div>
