<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/* @var $block \Aheadworks\Sarp\Block\Customer\Subscriptions */

// @codingStandardsIgnoreFile
?>
<?php
    $profiles = $block->getProfiles();
?>
<?php if ($profiles && count($profiles)): ?>
    <div class="table-wrapper aw-sarp-customer-subscriptions">
        <table class="data table">
            <caption class="table-caption"><?php echo $block->escapeHtml(__('Subscriptions')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col reference-id"><?php echo $block->escapeHtml(__('Payment Reference ID')) ?></th>
                    <th scope="col" class="col status"><?php echo $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col products"><?php echo $block->escapeHtml(__('Product(s)')) ?></th>
                    <th scope="col" class="col subscription-plan"><?php echo $block->escapeHtml(__('Subscription Plan')) ?></th>
                    <th scope="col" class="col last-order-date"><?php echo $block->escapeHtml(__('Last Order Date')) ?></th>
                    <th scope="col" class="col created-at"><?php echo $block->escapeHtml(__('Created At')) ?></th>
                    <th scope="col" class="col actions"><?php echo $block->escapeHtml(__('Actions')) ?></th>
                </tr>
            </thead>
            <tbody>
            <?php
                /* @var $profile \Aheadworks\Sarp\Api\Data\ProfileInterface */
            ?>
            <?php foreach ($profiles as $profile): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Payment Reference ID')) ?>" class="col reference-id">
                        <?php /* @noEscape */ echo $profile->getReferenceId() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status">
                        <?php echo $block->escapeHtml($block->getStatusLabel($profile->getStatus())) ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Product(s)')) ?>" class="col products">
                        <ul>
                        <?php foreach ($profile->getItems() as $item): ?>
                            <li>
                                <?php if ($block->isProductExists($item['product_id']) && $block->hasProductUrl($item['product_id'])): ?>
                                    <a href="<?php echo $block->escapeUrl($block->getProductUrl($item['product_id'])) ?>">
                                        <span><?php echo $block->escapeHtml($item['name']) ?></span>
                                    </a>
                                <?php else: ?>
                                    <?php echo $block->escapeHtml($item['name']) ?>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Subscription Plan')) ?>" class="col subscription-plan">
                        <?php echo $block->escapeHtml($profile->getSubscriptionPlanName()) ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Last Order Date')) ?>" class="col last-order-date">
                        <?php if ($profile->getLastOrderId()): ?>
                            <?php /* @noEscape */ echo $block->formatDate($profile->getLastOrderDate(), \IntlDateFormatter::MEDIUM) ?>
                        <?php endif; ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Created At')) ?>" class="col created-at">
                        <?php /* @noEscape */ echo $block->formatDate($profile->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php echo $block->escapeUrl($block->getViewUrl($profile->getProfileId())) ?>" class="action view">
                            <span><?php echo $block->escapeHtml(__('View')) ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="toolbar bottom"><?php /* @noEscape */ echo $block->getChildHtml('pager') ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?php echo $block->escapeHtml(__('You have created no subscriptions.')) ?></span>
    </div>
<?php endif ?>
