<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
	$quote	= $block->getProduct()->getMemberQuote();
	$_items = $block->getReviewsCollection()->getItems();
    $format	= $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
<div class="container block review-list" id="customer-reviews">
	
	<div class="total-score">
		<div class="content">
			<div class="box">
				TOTAL SCORE
				<strong>4.7</strong>
				OUT OF 5
			</div>
		</div>
	</div>

	<?php if ($quote) : ?>
    <div class="block-title">WHAT MEMBERS ARE SAYING</div>
	<blockquote class="block-subtitle"><?= nl2br($block->escapeHtml($quote)); ?></blockquote>
	<?php endif; ?>

    <div class="block-content">
        <?php /* <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div> */ ?>
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <?php if (count($_review->getRatingVotes())): ?>
                    <div class="review-ratings">
                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <?php /* <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span> */ ?>
                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
	                        <meta itemprop="worstRating" content = "1"/>
	                        <meta itemprop="bestRating" content = "100"/>
                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
	                    
	                    <div class="review-details">
		                    <p class="review-author">
			                    <?php /* <span class="review-details-label"><?php echo __('Review by')?></span> */ ?>
			                    <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
		                    </p>
		                    <p class="review-verified"><span class="icon-ok-circled"></span>Verified Buyer</p>
		                    <p class="review-date">
			                    <?php /* <span class="review-details-label"><?php echo __('Posted on') ?></span> */ ?>
			                    <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
		                    </p>
	                    </div>
	                    
                    </div>
                <?php endif; ?>
                <div class="review-content" itemprop="description">
	                <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
                    <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
	                
	                <ul class="rating-details">
		                <li>
			                <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
				                <span class="label rating-label">Quality</span>
				                <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
					                <meta itemprop="worstRating" content = "1"/>
					                <meta itemprop="bestRating" content = "100"/>
					                <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
	                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
				                </div>
				                <span class="label rating-label">4.8/5</span>
			                </div>
		                </li>
		                <li>
			                <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
				                <span class="label rating-label">Value</span>
				                <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
					                <meta itemprop="worstRating" content = "1"/>
					                <meta itemprop="bestRating" content = "100"/>
					                <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
	                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
				                </div>
				                <span class="label rating-label">4.5/5</span>
			                </div>
		                </li>
	                </ul>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
	        
	        <a href="#" class="prev"><span class="icon-left-dir"></span></a>
	        <span class="pager">1-3 OF 23 REVIEWS</span>
	        <a href="#" class="next"><span class="icon-right-dir"></span></a>
	        
        </div>
    </div>
</div>
<?php endif;?>
