<style type="text/css">
	.config-checkbox { border:1px solid #eee !important; }
</style>
<?php if ($block->getApi()->getClient()->isAccessTokenExpired()):?>
	<a style="display:inline-block; 
		height:30px; 
		border:1px solid #4285F4; 
		line-height:30px; 
		padding:0px 10px 0px 10px; 
		background:transparent -moz-linear-gradient(center top , #4387FD, #4683EA) repeat scroll 0% 0%; 
		background: -webkit-gradient(linear, center top, center bottom, from(#917c4d), to(#ffffff));
		background: -webkit-linear-gradient(#4387FD, #4683EA);
		background: -moz-linear-gradient(#4387FD, #4683EA);
		background: -o-linear-gradient(#4387FD, #4683EA);
		background: -ms-linear-gradient(#4387FD, #4683EA);
		background: linear-gradient(#4387FD, #4683EA);
		color:#fff; 
		text-decoration:none; 
		font-size:13px; 
		font-family:Arial, sans-serif; 
		font-weight:bold; 
		border-radius:2px;
		margin-bottom:5px;" href="<?php echo $block->getApi()->getClient()->createAuthUrl()?>">Sign in to Google</a>
<?php else: ?>
	<div>
		<div style="margin:0px 0px 10px 0px"><strong style="text-transform: uppercase">SELECT ITEMS TO CREATE IN YOUR GOOGLE TAG MANAGER ACCOUNT</strong></div>
		<div style="margin:0px 0px 10px 0px">The following items will be created next time you click "Save config" button.</div>
	</div>
	<div>
		<div><label for="ec_api_variables"><input type="checkbox" class="config-checkbox" name="args[]" value="ec_api_variables" id="ec_api_variables" /> Create variables</label></div>
		<div><label for="ec_api_triggers"><input type="checkbox" class="config-checkbox" name="args[]" value="ec_api_triggers" id="ec_api_triggers" /> Create triggers</label></div>
		<div><label for="ec_api_tags"><input type="checkbox" class="config-checkbox" name="args[]" value="ec_api_tags" id="ec_api_tags" /> Create tags</label></div>
		<div>
			<a href="javascript:void(0)" onclick="toggleApi(this)" style="display:block; margin-top:10px">Check all</a>
			<script>
				require(['jquery'],function($)
				{
					window.toggleApi = function(target)
					{
						$(target).parents('div').eq(1).find(':checkbox').prop('checked', true);

						return false;
					};
				});
			</script>
		</div>
	</div>
	<div style="margin:10px 0px 10px 0px">
		Make sure Container ID and Account ID are present and your account is authorised with corresponding permissions. If you don't know how to use the API, we've prepared a short video on YouTube available in 1080p<br /><br /> <a href="https://www.youtube.com/watch?v=U8dK95FRP1w" target="_blank">Magento 2 Google Tag Manager API</a>
	</div>
<?php endif ?>