<?php
/* @var $block \Aheadworks\Sarp\Block\Customer\Subscription\Info\Address\Form */

// @codingStandardsIgnoreFile
?>
<?php
    $address = $block->getAddress();
    $formHtmlId = $address->getAddressType() . '-address-form';
?>
<form class="form-address-edit"
      id="<?php echo $block->escapeHtml($formHtmlId) ?>"
      action="<?php echo $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      data-mage-init='{"awSarpAddressValidation":{}}'>
    <?php echo $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="profile_id" value="<?php echo $block->escapeHtml($address->getProfileId()) ?>">
    <input type="hidden" name="address_type" value="<?php echo $block->escapeHtml($address->getAddressType()) ?>">
    <?php if ($block->isPrefixVisible()): ?>
        <div class="field prefix<?php if ($block->isPrefixRequired()) /* @noEscape */ echo ' required' ?>">
            <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('prefix')) ?>">
                <span><?php echo $block->escapeHtml($block->getAttributeStoreLabel('prefix')) ?></span>
            </label>
            <div class="control">
                <?php if ($block->getPrefixOptions() === false): ?>
                    <input type="text"
                           id="<?php echo $block->escapeHtml($block->getFieldHtmlId('prefix')) ?>"
                           name="prefix"
                           value="<?php echo $block->escapeHtml($address->getPrefix()) ?>"
                           title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('prefix')) ?>"
                           class="input-text <?php echo $block->escapeHtml($block->getAttributeFrontendClass('prefix')) ?>" <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?php echo $block->escapeHtml($block->getFieldHtmlId('prefix')) ?>"
                            name="prefix"
                            title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('prefix')) ?>"
                            class="<?php echo $block->escapeHtml($block->getAttributeFrontendClass('prefix')) ?>" <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                        <?php foreach ($block->getPrefixOptions() as $option): ?>
                            <option value="<?php echo $block->escapeHtml($option) ?>"<?php if ($address->getPrefix() == $option): ?> selected="selected"<?php endif; ?>>
                                <?php echo $block->escapeHtml(__($option)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="field firstname required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('firstname')) ?>">
            <span><?php echo $block->escapeHtml($block->getAttributeStoreLabel('firstname')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('firstname')) ?>"
                   name="firstname"
                   value="<?php echo $block->escapeHtml($address->getFirstname()) ?>"
                   title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('firstname')) ?>"
                   class="input-text <?php echo $block->escapeHtml($block->getAttributeFrontendClass('firstname')) ?>"
                   data-validate="{required:true}">
        </div>
    </div>
    <?php if ($block->isMiddlenameVisible()): ?>
        <div class="field middlename<?php if ($block->isMiddlenameRequired()) /* @noEscape */ echo ' required' ?>">
            <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('middlename')) ?>">
                <span><?php echo $block->escapeHtml($block->getAttributeStoreLabel('middlename')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="<?php echo $block->escapeHtml($block->getFieldHtmlId('middlename')) ?>"
                       name="middlename"
                       value="<?php echo $block->escapeHtml($address->getMiddlename()) ?>"
                       title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('middlename')) ?>"
                       class="input-text <?php echo $block->escapeHtml($block->getAttributeFrontendClass('middlename')) ?>" <?php if ($block->isMiddlenameRequired()) echo ' data-validate="{required:true}"' ?>>
            </div>
        </div>
    <?php endif; ?>
    <div class="field lastname required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('lastname')) ?>">
            <span><?php echo $block->escapeHtml($block->getAttributeStoreLabel('lastname')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('lastname')) ?>"
                   name="lastname"
                   value="<?php echo $block->escapeHtml($address->getLastname()) ?>"
                   title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('lastname')) ?>"
                   class="input-text <?php echo $block->escapeHtml($block->getAttributeFrontendClass('lastname')) ?>"
                   data-validate="{required:true}">
        </div>
    </div>
    <?php if ($block->isSuffixVisible()): ?>
        <div class="field suffix<?php if ($block->isSuffixRequired()) /* @noEscape */ echo ' required' ?>">
            <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('suffix')) ?>">
                <span><?php echo $block->escapeHtml($block->getAttributeStoreLabel('suffix')) ?></span>
            </label>
            <div class="control">
                <?php if ($block->getPrefixOptions() === false): ?>
                    <input type="text"
                           id="<?php echo $block->escapeHtml($block->getFieldHtmlId('suffix')) ?>"
                           name="suffix"
                           value="<?php echo $block->escapeHtml($address->getSuffix()) ?>"
                           title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('suffix')) ?>"
                           class="input-text <?php echo $block->escapeHtml($block->getAttributeFrontendClass('suffix')) ?>" <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?php echo $block->escapeHtml($block->getFieldHtmlId('suffix')) ?>"
                            name="suffix"
                            title="<?php echo $block->escapeHtml($block->getAttributeStoreLabel('suffix')) ?>"
                            class="<?php echo $block->escapeHtml($block->getAttributeFrontendClass('suffix')) ?>" <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                        <?php foreach ($block->getSuffixOptions() as $option): ?>
                            <option value="<?php echo $block->escapeHtml($option) ?>"<?php if ($address->getSuffix() == $option): ?> selected="selected"<?php endif; ?>>
                                <?php echo $block->escapeHtml(__($option)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="field street required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('street1')) ?>">
            <span><?php echo $block->escapeHtml(__('Street Address')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('street1')) ?>"
                   name="street[]"
                   value="<?php echo $block->escapeHtml($address->getStreet()[0]) ?>"
                   title="<?php echo $block->escapeHtml(__('Street Address')) ?>"
                   class="input-text"
                   data-validate="{required:true}"/>
        </div>
    </div>
    <div class="field street2">
        <?php
            $address2 = isset($address->getStreet()[1]) ? $address->getStreet()[1] : '';
        ?>
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('street2')) ?>">
            <span><?php echo $block->escapeHtml(__('Street Address 2')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="street[]"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('street2')) ?>"
                   value="<?php echo $block->escapeHtml($address2) ?>"
                   title="<?php echo $block->escapeHtml(__('Street Address 2')) ?>"
                   class="input-text">
        </div>
    </div>
    <div class="field region required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('region_id')) ?>">
            <span><?php echo $block->escapeHtml(__('State/Province')) ?></span>
        </label>
        <div class="control">
            <select id="<?php echo $block->escapeHtml($block->getFieldHtmlId('region_id')) ?>"
                    name="region_id"
                    title="<?php echo $block->escapeHtml(__('State/Province')) ?>"
                    class="validate-select" <?php /* @noEscape */ echo $block->isOptionalRegionAllowed() ? '' : ' disabled="disabled"'  ?>>
                <option value=""><?php echo $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
            </select>
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('region')) ?>"
                   name="region"
                   value="<?php echo $block->escapeHtml($address->getRegion()) ?>"
                   title="<?php echo $block->escapeHtml(__('State/Province')) ?>"
                   class="input-text" <?php /* @noEscape */ echo $block->isOptionalRegionAllowed() ? '' : ' disabled="disabled"' ?>
                   data-validate="{required:true}">
        </div>
    </div>
    <div class="field city required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('city')) ?>">
            <span><?php echo $block->escapeHtml(__('City')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('city')) ?>"
                   name="city"
                   value="<?php echo $block->escapeHtml($address->getCity()) ?>"
                   title="<?php echo $block->escapeHtml(__('City')) ?>"
                   class="input-text"
                   data-validate="{required:true}">
        </div>
    </div>
    <div class="field zip required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('zip')) ?>">
            <span><?php echo $block->escapeHtml(__('Zip/Postal Code')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('zip')) ?>"
                   name="postcode"
                   value="<?php echo $block->escapeHtml($address->getPostcode()) ?>"
                   title="<?php echo $block->escapeHtml(__('Zip/Postal Code')) ?>"
                   class="input-text validate-zip-international"
                   data-validate="{required:true}">
        </div>
    </div>
    <div class="field country required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('country')) ?>">
            <span><?php echo $block->escapeHtml(__('Country')) ?></span>
        </label>
        <div class="control">
            <select id="<?php echo $block->escapeHtml($block->getFieldHtmlId('country')) ?>"
                    name="country_id"
                    title="<?php echo $block->escapeHtml(__('Country')) ?>"
                    data-validate="{'validate-select':true}"
                    >
                <?php foreach ($block->getCountryOptions() as $option): ?>
                    <option value="<?php echo $block->escapeHtml($option['value']) ?>"<?php if ($address->getCountryId() == $option['value']): ?> selected="selected"<?php endif; ?>>
                        <?php echo $block->escapeHtml(__($option['label'])) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field company">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('company')) ?>">
            <span><?php echo $block->escapeHtml(__('Company')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('company')) ?>"
                   name="company"
                   value="<?php echo $block->escapeHtml($address->getCompany()) ?>"
                   title="<?php echo $block->escapeHtml(__('Company')) ?>"
                   class="input-text">
        </div>
    </div>
    <div class="field telephone required">
        <label class="label" for="<?php echo $block->escapeHtml($block->getFieldHtmlId('telephone')) ?>">
            <span><?php echo $block->escapeHtml(__('Phone Number')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   id="<?php echo $block->escapeHtml($block->getFieldHtmlId('telephone')) ?>"
                   name="telephone"
                   value="<?php echo $block->escapeHtml($address->getTelephone()) ?>"
                   title="<?php echo $block->escapeHtml(__('Phone Number')) ?>"
                   class="input-text"
                   data-validate="{required:true}">
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Save')) ?>"
                    class="action save-address"
                    data-role="address-submit-action">
                <span><?php echo $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action cancel" href="#" data-role="address-cancel-action">
                <span><?php echo $block->escapeHtml(__('Cancel')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#<?php echo $block->escapeHtml($block->getFieldHtmlId('country')) ?>": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @noEscape */ echo \Zend_Json::encode($block->isOptionalRegionAllowed()) ?>,
                "regionListId": "#<?php echo $block->escapeHtml($block->getFieldHtmlId('region_id')) ?>",
                "regionInputId": "#<?php echo $block->escapeHtml($block->getFieldHtmlId('region')) ?>",
                "postcodeId": "#<?php echo $block->escapeHtml($block->getFieldHtmlId('zip')) ?>",
                "form": "#<?php echo $block->escapeHtml($formHtmlId) ?>",
                "regionJson": <?php /* @noEscape */ echo $block->getRegionJson() ?>,
                "defaultRegion": "<?php /* @noEscape */echo (int) $address->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @noEscape */ echo $this->getCountriesWithOptionalZip() ?>
            }
        }
    }
</script>
