<?php
$howToCollection = $this->getProduct()->getHowTo();

if ($howToCollection && $howToCollection != '[]'):
	$i = 1;
	$_helper = $this->helper('Eleanorsoft\HowTo\Helper\Data');
	$howToCollection = $_helper->prepareHowToGrid($howToCollection);
?>
<ul class="items howto-items">
	<?php foreach ($howToCollection as $item): ?>
		<li class="item howto-item">
			<img src="<?= $this->escapeHtml($item->imageUrl); ?>" alt="<?= $this->escapeHtml($item->description); ?>" class="howto-image" />
			<div class="howto-content"><?= $i++ ?>. <?= $this->escapeHtml($item->description); ?></div>
		</li>
	<?php endforeach; ?>
</ul>
<?php else: ?>
	<style>div#tab-label-howto{display:none;}</style>
<?php endif; ?>