<ul class="items howto-items">
	<li class="item howto-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/how-to_1.png" alt=""
		     class="howto-image" />
		<div class="howto-content">1. Rinse shaveable area with warm water.</div>
	</li>
	<li class="item howto-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/how-to_2.png" alt=""
		     class="howto-image" />
		<div class="howto-content">2. Dispense 1-2 pumps of oil onto hands and rub palms together</div>
	</li>
	<li class="item howto-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/how-to_3.png" alt=""
		     class="howto-image" />
		<div class="howto-content">3. Massage a thin layer of oil onto shaveable area</div>
	</li>
</ul>