<ul class="items ingredient-items">
	<li class="item ingredient-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/ingredients_01.png" alt=""
			 class="ingredient-image" />
		<div class="ingredient-content">
			<div class="ingredient-title">BLACKJACK BOTANICAL</div>
			Daisy flower extract contains antioxidants, malic, and skin-firming natural tartaric acids that can help you fight pigmentation, sunspots, wrinkles and sagging skin.
		</div>
	</li>
	<li class="item ingredient-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/ingredients_02.png" alt=""
		     class="ingredient-image" />
		<div class="ingredient-content">
			<div class="ingredient-title">DAISY FLOWER EXTRACT</div>
			Daisy flower extract contains antioxidants, malic, and skin-firming natural tartaric acids that can help you fight pigmentation, sunspots, wrinkles and sagging skin.
		</div>
	</li>
	<li class="item ingredient-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/ingredients_03.png" alt=""
		     class="ingredient-image" />
		<div class="ingredient-content">
			<div class="ingredient-title">WILLOWBACK EXTRACT</div>
			Daisy flower extract contains antioxidants, malic, and skin-firming natural tartaric acids that can help you fight pigmentation, sunspots, wrinkles and sagging skin.
		</div>
	</li>
	<li class="item ingredient-item">
		<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/ingredients_04.png" alt=""
		     class="ingredient-image" />
		<div class="ingredient-content">
			<div class="ingredient-title">BLACKJACK BOTANICAL</div>
			Daisy flower extract contains antioxidants, malic, and skin-firming natural tartaric acids that can help you fight pigmentation, sunspots, wrinkles and sagging skin.
		</div>
	</li>
</ul>