<div class="container satisfaction">
	
	<div class="satisfaction-title">
		<div class="box">
			<div class="title">100% SATISFACTION GUARANTEED</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col">
			<div class="item">
				<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/satisfaction_1.png" alt="" />
				<div class="title">LIGHT WEIGHT FORMULA</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat justo porttitor,  mollis diam iaculis. Duis a consequat urna. Proin maximus ante id massa.</p>
			</div>
		</div>
		<div class="col">
			<div class="item">
				<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/satisfaction_2.png" alt="" />
				<div class="title">NO SHINE/MATT</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat justo porttitor,  mollis diam iaculis. Duis a consequat urna. Proin maximus ante id massa.</p>
			</div>
		</div>
		<div class="col">
			<div class="item">
				<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/satisfaction_3.png" alt="" />
				<div class="title">RANCH TO BOTTLE</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat justo porttitor,  mollis diam iaculis. Duis a consequat urna. Proin maximus ante id massa.</p>
			</div>
		</div>
	</div>
	
</div>


<div class="container-fluid built-for-life">
	<div class="container">
		<div class="title">OUR PRODUCTS ARE BUILT FOR LIFE</div>
		<p>Crafted with pride, using unrivaled ingredients for unrivaled results. Because you’re worth it.</p>
		
		<div class="row-container">
			<div class="row">
				<div class="col wborder">
					<div class="item">
						<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/built-for-life_1.png" alt="" />
						<div class="title">CONQUER DAILY LIFE</div>
						<p>Work, stress, traffic & smog all take a toll
							on our skin. Our products help you
							revitalize so you can stay on top.</p>
					</div>
				</div>
				<div class="col">
					<div class="item">
						<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/built-for-life_2.png" alt="" />
					</div>
				</div>
				<div class="col">
					<div class="item">
						<div class="title">AVENTURE AWAITS</div>
						<p>The spirit of the outdoors is at the core of our
							DNA. From campfires to summit pushes
							our products thrive in harsh environments.</p>
					</div>
				</div>
			</div>
			
			<div class="row">
				<div class="col">
					<div class="item">
						<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/built-for-life_3.png" alt="" />
					</div>
				</div>
				<div class="col wborder">
					<div class="item">
						<div class="title">TRAVEL LIKE YOU MEAN IT</div>
						<p>Arrive at your destination feeling confident
							and refreshed. Spend a couple minutes and
							feel like you walked out of a spa.</p>
					</div>
				</div>
				<div class="col">
					<div class="item">
						<img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/product/built-for-life_4.png" alt="" />
						<div class="title">RELAX AND PROTECT</div>
						<p>Our moisturizer with SPF guards your face
							during the day while the cleanser and serum
							help repair and rejuvanate at night.</p>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>
