<?php
$featuredReview = $block->getLayout()
	->createBlock('Eleanorsoft\FeaturedReview\Block\FeaturedReview')
	->getFeaturedReview($block->getProduct());
$detail = $featuredReview->getDetail();
$nickname = $featuredReview->getNickname();
?>
<div class="product-as_seen_on">
	<div class="title">As Seen On:</div>
	<a href="#"><img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/organic-spa.png" alt="" /></a>
	<a href="#"><img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/forbes.png" alt="" /></a>

	<?php if ($detail && $nickname) : ?>
		<blockquote><?= $block->escapeHtml($detail); ?>
			<span>—<?= $block->escapeHtml($nickname); ?></span></blockquote>
	<?php endif; ?>
</div>