<div class="product-as_seen_on">
	<div class="title">As Seen On:</div>
	<a href="#"><img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/organic-spa.png" alt="" /></a>
	<a href="#"><img src="<?php echo $this->getUrl('pub/media'); ?>/wysiwyg/forbes.png" alt="" /></a>
	
	<blockquote>The reviews all seemed too good to be true, but it works. it really works. my skin has never looked this good. it’s so bright and clear. i don’t have to wear make up anymore.
		<span>—JAKE, 34</span></blockquote>
</div>