<?php
/** @var \Atak\Praise\Block\Listing $block */

$list = $block->getItems();

?>

<div class="container-fluid home-articles">
    <?php foreach ($list as $item) : ?>
    <div class="row">
        <?php if ($item->getVideoPosition() == 'left') : ?>
            <div class="col">
                <div class="video-block" data-video-id="<?= $block->escapeHtml($block->getYouTubeCode($item)); ?>"
                     style="background-image: url('<?= $block->escapeHtml($block->getImageUrl($item)); ?>')">
                </div>
            </div>
            <div class="col">
                <div class="article-content">
                    <h3><?= $block->escapeHtml($item->getName()); ?></h3>
                    <?= nl2br($block->escapeHtml($item->getText())); ?>
                    <div class="text-right">
                        <a href="<?= $block->escapeHtml($item->getButtonLink()); ?>" class="action primary">
                            <?= $block->escapeHtml($item->getButtonText()); ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php else : ?>
            <div class="col">
                <div class="article-content">
                    <h3><?= $block->escapeHtml($item->getName()); ?></h3>
                    <?= nl2br($block->escapeHtml($item->getText())); ?>
                    <div class="text-right">
                        <a href="<?= $block->escapeHtml($item->getButtonLink()); ?>" class="action primary">
                            <?= $block->escapeHtml($item->getButtonText()); ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="video-block" data-video-id="<?= $block->escapeHtml($block->getYouTubeCode($item)); ?>"
                     style="background-image: url('<?= $block->escapeHtml($block->getImageUrl($item)); ?>')">
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
