<script>
	require(['jquery'],function($)
	{
		(function($, dataLayer)
		{
			var events = 
			{
				addToCart: function()
				{
					<?php
					/**
					 * @todo Complete impementation
					 */
					?>
				},
				removeFromCart: function()
				{
					<?php
					/**
					 * @todo Complete impementation
					 */
					?>
				},
				productClick: function()
				{
					<?php
					/**
					 * @todo Complete impementation
					 */
					?>	
				}
			};

			$.each(events, function(event, callback)
			{
				var elements = $('[data-event]').filter(function()
				{
					return $(this).data('event') == event;
				});

				elements.each(function()
				{
					$(this).off('click.ec').on('click.ec', callback);

					<?php
					/**
					 * Custom events
					 */
					?>
					$(this).on(
					{
						addToCart: function()
						{
							<?php
							/**
							 * @todo Implement your own logic at "Add to cart" click
							 */
							?>
						},
						removeFromCart: function()
						{
							<?php
							/**
							 * @todo Implement your own logic at "Add to cart" click
							 */
							?>
						},
						productClick: function()
						{
							<?php
							/**
							 * @todo Implement your own logic at "Add to cart" click
							 */
							?>
						}
					});
				});
			});
			
		})($, dataLayer);
	});
</script>