<script>

	<?php
	/**
	 * Magento 2 Google Tag Manager Enhanced Ecommerce Tracking
	 *
	 * @author Anowave
	 * @see http://www.anowave.com/marketplace/magento-2-extensions/magento-2-google-tag-manager-enhanced-ecommerce-ua-tracking/
	 * @copyright 2017 Anowave
	 */
	?>

	window.dataLayer = window.dataLayer || [], collection = [];

	<?php
	/**
	 * AEC Constants
	 */
	?>
	
	AEC.Const = 
	{
		TIMING_CATEGORY_ADD_TO_CART:		'Add To Cart Time',
		TIMING_CATEGORY_REMOVE_FROM_CART:	'Remove From Cart Time',
		TIMING_CATEGORY_PRODUCT_CLICK:		'Product Detail Click Time',
		TIMING_CATEGORY_CHECKOUT:			'Checkout Time',
		TIMING_CATEGORY_CHECKOUT_STEP:		'Checkout Step Time'
	};

	AEC.Const.URL 					= '<?php echo $block->getHelper()->getStore()->getBaseUrl() ?>';
	AEC.Const.VARIANT_DELIMITER 	= '<?php echo \Anowave\Ec\Helper\Data::VARIANT_DELIMITER ?>';
	AEC.Const.VARIANT_DELIMITER_ATT = '<?php echo \Anowave\Ec\Helper\Data::VARIANT_DELIMITER_ATT ?>';

	<?php
	/**
	 * Checkout step indexes. Should match funnel configuration in GA
	 */
	?>
	
	AEC.Const.CHECKOUT_STEP_SHIPPING = <?php echo \Anowave\Ec\Helper\Constants::CHECKOUT_STEP_SHIPPING ?>;
	AEC.Const.CHECKOUT_STEP_PAYMENT  = <?php echo \Anowave\Ec\Helper\Constants::CHECKOUT_STEP_PAYMENT ?>;

	<?php
	/**
	 * Define messages
	 */
	?>
	
	AEC.Message = 
	{
		confirmRemove: '<?php echo __('Are you sure you would like to remove this item from the shopping cart?') ?>'
	};
			
	AEC.storeName 			= '<?php echo $block->getHelper()->getStoreName() ?>';
	AEC.currencyCode	 	= '<?php echo $block->getHelper()->getStore()->getCurrentCurrencyCode() ?>';
	AEC.useDefaultValues 	=  <?php echo json_encode($block->getHelper()->useDefaultValues()) ?>;
	AEC.facebook 			=  <?php echo json_encode($block->getHelper()->facebook()) ?>;

	<?php
	/**
	 * Get super attributes
	 */
	?>
	
	AEC.SUPER = <?php echo $block->getHelper()->getSuper() ?>;

	<?php
	/**
	 * Mutations
	 */
	?>
	
</script>
<?php
/**
 * Facebook Pixel Tracking
 */
?>
<?php echo $block->getHelper()->getFacebookPixelCode() ?>