<?php echo $block->getChildHtml('ec_datalayer') ?>
<script>

	var EC = [], Purchase = [];

	/* Dynamic remarketing */
	window.google_tag_params = window.google_tag_params || {};

	/* Default pagetype */
	window.google_tag_params.ecomm_pagetype = '<?php echo $block->getPageType() ?>';

	/* Grouped products collection */
	window.G = [];

	/**
	 * Global revenue 
	 */
	window.revenue = 0;

	/**
	 * DoubleClick
	 */
	window.DoubleClick = 
	{
		DoubleClickRevenue:	 	0,
		DoubleClickTransaction: 0,
		DoubleClickQuantity: 	0
	};
	
	var visitor = <?php echo $block->getVisitorPush() ?>;

	<?php if ($block->getOrderIds()):?>

		var data = <?php echo $block->getPurchasePush($block) ?>;
			
		/**
		 * Push transaction
	 	 */
		dataLayer.push(data);

		<?php $google_tag_params = $block->getPurchaseGoogleTagParams($block) ?>

		/**
		 * AdWords Dynamic Remarketing page type
		 */
		window.google_tag_params.ecomm_pagetype		= '<?php echo __('purchase') ?>';

		/**
		 * AdWords Dynamic Remarketing value(s)
		 */
		window.google_tag_params.ecomm_prodid 		= <?php echo json_encode($google_tag_params->ecomm_prodid) ?>;
		window.google_tag_params.ecomm_pvalue 		= <?php echo json_encode($google_tag_params->ecomm_pvalue) ?>;
		window.google_tag_params.ecomm_pname 		= <?php echo json_encode($google_tag_params->ecomm_pname) ?>;
		window.google_tag_params.ecomm_totalvalue  	= <?php echo $google_tag_params->ecomm_totalvalue ?>;
		window.google_tag_params.returnCustomer 	= <?php echo $block->getHelper()->getIsReturnCustomer() ?>;

		/**
		 * AdWords Conversion Tracking
		 */
		<?php if ($block->getAdwords()->getGoogleConversionId()) : ?>

			window.google_conversion_id 		= <?php echo $block->getAdwords()->getGoogleConversionId() ?>;
			
			window.google_conversion_value 		= '<?php echo $block->getRevenue() ?>';
			window.google_conversion_language 	= '<?php echo $block->getAdwords()->getGoogleConversionLanguage() ?>';
			window.google_conversion_format 	= '<?php echo $block->getAdwords()->getGoogleConversionFormat() ?>';
			window.google_conversion_label 		= '<?php echo $block->getAdwords()->getGoogleConversionLabel() ?>';
			window.google_conversion_color		= '<?php echo $block->getAdwords()->getGoogleConversionColor() ?>';
			window.google_conversion_currency 	= '<?php echo $block->getAdwords()->getGoogleConversionCurrency() ?>';
		
		<?php endif ?>

		<?php if ($block->getHelper()->facebook()): ?>
		
			if ("undefined" !== typeof fbq)
			{
				if ("undefined" !== typeof fbq)
				{
					var content_ids = [], content_length = data.ecommerce.purchase.products.length;

					for (i = 0, l = data.ecommerce.purchase.products.length; i < l; i++)
					{
						content_ids.push(data.ecommerce.purchase.products[i].id);
					}

					window.content_ids = content_ids;

					<?php $key = $block->getHelper()->getFacebookValueKey() ?>
		
					fbq("track", "Purchase", 
					{
						content_type: 	'product',
						content_ids:	content_ids,
						num_items:		content_length,
						value: 			data.facebook['<?php echo $key ?>'],
						currency: 		'<?php echo $block->getHelper()->getCurrency() ?>'
					});
				}
			}
			
		<?php endif ?>
	
	<?php endif ?>	
	<?php
	/**
	 * Push visitor data
	 */
	?>
	
	dataLayer.push(visitor);
	
</script>
<?php echo $block->getChildHtml('ec_impressions') ?>
<?php echo $block->getChildHtml('ec_search') ?>
<?php echo $block->getChildHtml('ec_detail') ?>
<?php echo $block->getChildHtml('ec_cart') ?>
<?php echo $block->getHeadSnippet() ?>
<?php
/**
 * Persistent dataLayer[] support
 */
?>

<script>AEC.Persist.merge()</script>

<?php
/**
 * AdWords Conversion Tracking
 */
?>
<?php if ($block->getHelper()->isAdwordsConversionTrackingActive()):?>
	<?php if ($block->getOrders() && $block->getAdwords()->getGoogleConversionId()) : ?>
		<script src="//www.googleadservices.com/pagead/conversion.js"></script>
	    <?php foreach ($block->getOrders() as $order): ?>
	            <noscript><img height=1 width=1 border=0 src="//www.googleadservices.com/pagead/conversion/<?php echo $block->getAdwords()->getGoogleConversionId() ?>/?value=<?php echo $block->getRevenue() ?>&label=<?php echo $block->getAdwords()->getGoogleConversionLabel() ?>&script=0"></noscript>
	    <?php endforeach ?>
	<?php endif ?>
<?php endif ?>