<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<style>
    .fieldset > .field.choice:before, .fieldset > .field.no-label:before {
        padding: 0;
        float: none;
    }
    div.mage-error[generated] {
        margin-top: -8px;
        margin-bottom: -9px;
    }
</style>
<div id="edit-address-modal" style="display: none;">
<form data-mage-init='{"validation": {}}' class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
        <?php /* <div class="field company">
            <label class="label" for="company"><span><?php echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="<?php echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div> */ ?>
        <?php /* <div class="field fax">
            <label class="label" for="fax"><span><?php echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="fax" id="fax" title="<?php echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
            </div>
        </div> */ ?>
    </fieldset>
    <fieldset class="fieldset">
	    
	    <div class="field country required">
		    <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
		    <div class="control">
			    <?php echo $block->getCountryHtmlSelect() ?>
		    </div>
	    </div>
	    
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <legend for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend>
            <div class="control">
	            <div class="field">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"  />
	            </div>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Appartment/Floor/Suite', $_i+1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php /* @escapeNotVerified */ echo __('State') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
	
	    <div class="field telephone required">
		    <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
		    <div class="control">
			    <input type="text" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone">
		    </div>
	    </div>

        <div class="field choice set shipping">
            <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
            <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
        </div>

        <div class="field choice set billing">
            <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
            <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
        </div>

        <div class="message info" data-default-billing-label><?php /* @escapeNotVerified */ echo __("It's a default billing address") ?></div>
        <div class="message info" data-default-shipping-label><?php /* @escapeNotVerified */ echo __("It's a default shipping address") ?></div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <?php /* <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo __('Go back') ?></span></a>
        </div> */ ?>
    </div>
</form>
</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
	require([
			'jquery',
			'Magento_Ui/js/modal/modal',
            'mage/validation',
            'regionUpdater'
		],
		function($, modal) {
            var options = {
                    buttons: [],
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'EDIT ADDRESS'
                },
                $modal = $('#edit-address-modal'),
                formValidate = $('.form-address-edit'),
                actionUrl = '<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>',
                modalUi = {
                    city: $('#city'),
                    region: $('#region_id'),
                    country: $('#country'),
                    postCode: $('#zip'),
                    lastName: $('#lastname'),
                    telephone: $('#telephone'),
                    firstName: $('#firstname'),
                    billingLabel: $('[data-default-billing-label]'),
                    shippingLabel: $('[data-default-shipping-label]'),
                    streetAddress: $('#street_1'),
                    streetApartment: $('#street_2'),
                    primaryBilling: $('#primary_billing'),
                    primaryShipping: $('#primary_shipping')
                },
                addressUi = {
                    city: '[data-city]',
                    region: '[data-region-id]',
                    postCode: '[data-post-code]',
                    lastName: '[data-last-name]',
                    telephone: '[data-telephone]',
                    firstName: '[data-first-name]',
                    countryId: '[data-country-id]',
                    addressId: '[data-address-id]',
                    streetAddress: '[data-street-address]',
                    streetApartment: '[data-street-apartment]',
                    addressContainer: '[data-address-container]'
                },
                fillModalForm = function (element) {
                    var addressContainer = $(element).closest(addressUi.addressContainer),
                        editAction = actionUrl + 'id/' + $(element).closest(addressUi.addressId).data('address-id');

                    modalUi.billingLabel.hide();
                    modalUi.shippingLabel.hide();
                    formValidate.validation('clearError');
                    formValidate.attr('action', editAction);
                    modalUi.primaryBilling.attr('checked', false);
                    modalUi.primaryShipping.attr('checked', false);
                    modalUi.city.val(addressContainer.find(addressUi.city).text());
                    modalUi.region.val(addressContainer.find(addressUi.region).text());
                    modalUi.postCode.val(addressContainer.find(addressUi.postCode).text());
                    modalUi.lastName.val(addressContainer.find(addressUi.lastName).text());
                    modalUi.telephone.val(addressContainer.find(addressUi.telephone).text());
                    modalUi.firstName.val(addressContainer.find(addressUi.firstName).text());
                    modalUi.country.val(addressContainer.find(addressUi.countryId).text());
                    modalUi.streetAddress.val(addressContainer.find(addressUi.streetAddress).text());
                    modalUi.streetApartment.val(addressContainer.find(addressUi.streetApartment).text());

                    if (addressContainer.is('[data-address-billing]')) {
                        modalUi.billingLabel.show();
                        modalUi.primaryBilling.attr('checked', true);
                    }

                    if (addressContainer.is('[data-address-shipping]')) {
                        modalUi.shippingLabel.show();
                        modalUi.primaryShipping.attr('checked', true);
                    }
                },
                openModal = function (title) {
                    options.title = title;
                    modal(options, $modal);
                    $modal.modal('openModal');
                };

            formValidate.submit(function (e) {
                var element = $(this);

                if (element.valid()) {
                    element.find('[type=submit]').prop('disabled', true);
                }
            });
			$('.block-dashboard-addresses .action.edit').click(function (e) {
				e.preventDefault();
                fillModalForm(this);
                openModal('EDIT ADDRESS');

				return false;
			});
            $('.block-dashboard-addresses .action.add').click(function (e) {
                e.preventDefault();

                var element = $(this);

                modalUi.primaryBilling.attr('checked', false);
                modalUi.primaryShipping.attr('checked', false);

                if (element.hasClass('primary-billing')) {
                    modalUi.primaryBilling.attr('checked', true);
                }

                if (element.hasClass('primary-shipping')) {
                    modalUi.primaryShipping.attr('checked', true);
                }

                formValidate[0].reset();
                modalUi.billingLabel.hide();
                modalUi.shippingLabel.hide();
                openModal('ADD ADDRESS');

                return false;
            });
		}
	);
</script>