<?php
/* @var $block \Aheadworks\Sarp\Block\Cart */

// @codingStandardsIgnoreFile
?>

<?php if ($block->getCartItemsCount()): ?>
    <div id="aw-sarp-cart" data-role="loader-container" data-bind="scope:'cart'" class="aw-sarp-cart-container">
        <div id="aw-sarp-loader" data-role="cart-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                     alt="<?php /* @noEscape */ echo __('Loading...') ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#aw-sarp-cart": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.awSarpCheckoutConfig = <?php /* @noEscape */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        </script>
    </div>
<?php else: ?>
    <div class="cart-empty">
        <p><?php echo $block->escapeHtml(__('You have no items in your subscription cart.')) ?></p>
        <p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.',
                $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    </div>
<?php endif; ?>
