<?php
/** @var $block \Eleanorsoft\EndSubscriptionQuiz\Block\Adminhtml\Subscription\Info */

// @codingStandardsIgnoreFile
?>
<?php
    $profile = $block->getProfile();
?>
<div class="aw-sarp_subscription_page">
    <div class="subscription-page_title_wrapper">
        <div class="subscription-page_title_title">
            <h1><?php echo $block->escapeHtml(__('Subscription #%1', $profile->getReferenceId())) ?></h1>
        </div>
        <div class="subscription-page_title_status">
            <span><?php echo $block->escapeHtml($block->getStatusLabel()) ?><span>
        </div>
    </div>
    <?php if($block->getStatus() == \Aheadworks\Sarp\Model\Profile\Source\Status::CANCELLED): ?>
        <div style="clear:both;max-width:50%;margin-bottom:15px">
            <span><?php echo __('Cancellation Reason').': '.$block->escapeHtml($block->getReason()) ?><span>
        </div>
    <?php endif; ?>
    <table class="orders_subscription-plan_wrapper">
        <tbody>
            <tr>
                <td class="subscription-orders">
                    <?php /* @noEscape */ echo $block->getOrdersHtml() ?>
                </td>
                <td class="subscription-plan">
                    <?php /* @noEscape */ echo $block->getSubscriptionPlanHtml() ?>
                </td>
            </tr>
        </tbody>
    </table>
    <?php /* @noEscape */ echo $block->getProductsHtml() ?>
    <?php /* @noEscape */ echo $block->getAddressesHtml() ?>
</div>
