<?php
/* @var $block \Eleanorsoft\AheadworksSarp\Block\Customer\Subscription\Info\Plan */

// @codingStandardsIgnoreFile
?>
<?php
    $profile = $block->getProfile();
    $options = $block->toOptionArray();
?>

<div id="change-repeat-modal">
    <form class="form form-edit-account" action="<?php echo $block->escapeUrl($block->getChangeRepeat()) ?>" method="post" id="form-change-repeat">
        <fieldset class="fieldset info">
            <?php echo $block->getBlockHtml('formkey')?>
                <label class="label" for="erst_reason_select"><span><?= __('Change Repeat'); ?></span></label>
                <div class="control">
                    <select name="es_change_repeat_select">
                        <?php foreach ($options as $option): ?>
                            <option value="<?= $option['value'] ?>"><?= $option['label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="button"
                        title="<?php echo $block->escapeHtml(__('Change')) ?>"
                        class="action"
                        data-mage-init='{"awSarpSubscribeButton":{
                        "subscribeUrl": "<?php echo $block->escapeUrl($block->getChangeRepeat()) ?>",
                        "form":"#form-change-repeat",
                        "defaultTitle": "<?php echo 'Change' ?>"
                        }}'>
                    <span><?php echo $block->escapeHtml(__('Change')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<div class="block aw_sarp-customer-subscription_plan">
    <div class="block-title">
        <strong><?php echo $block->escapeHtml(__('Subscription Plan')) ?></strong>
    </div>
    <div class="block-content">
        <div id="box-plan-details" class="box">
            <div class="box-title">
                <span class="title"><?php echo $block->escapeHtml($profile->getSubscriptionPlanName()) ?></span>
            </div>
            <div class="box-content">
                <dl>
                    <dt class="label"><?php echo $block->escapeHtml(__('Number of Payments')) ?>:</dt>
                    <dd class="value">
                        <span>
                            <?php if ($profile->getTotalBillingCycles() > 0): ?>
                                <?php /* @noEscape */ echo $profile->getTotalBillingCycles() ?>
                            <?php else: ?>
                                <?php echo $block->escapeHtml(__('Infinite')) ?>
                            <?php endif; ?>
                        </span>
                    </dd>
                </dl>
                <dl>
                    <dt class="label"><?php echo $block->escapeHtml(__('Repeat')) ?>:</dt>
                    <dd class="value">
                        <span><?php echo $block->escapeHtml($block->formatRepeatValue($profile)) ?></span>
                        <button type="button" id="change-repeat"><?php echo $block->escapeHtml(__('Change')) ?></button>
                    </dd>
                </dl>
                <dl>
                    <dt class="label"><?php echo $block->escapeHtml(__('Start')) ?>:</dt>
                    <dd class="value">
                        <span><?php /* @noEscape */ echo $block->formatDate($profile->getStartDate(), \IntlDateFormatter::MEDIUM) ?></span>
                    </dd>
                </dl>
                <dl>
                    <dt class="label"><?php echo $block->escapeHtml(__('Each Payment (except Trial Period, excl. tax and shipping)')) ?>:</dt>
                    <dd class="value">
                        <?php /* @noEscape */ echo $block->formatProfileAmount($profile->getBaseSubtotal(), $profile->getBaseCurrencyCode()) ?>
                    </dd>
                </dl>
                <?php if ($profile->getIsTrialPeriodEnabled() && $profile->getTrialSubtotal() > 0): ?>
                    <dl>
                        <dt class="label"><?php echo $block->escapeHtml(__('Trial Period')) ?>:</dt>
                        <dd class="value">
                            <span><?php echo $block->escapeHtml(__($profile->getTrialTotalBillingCycles() > 1 ? '%1 payments' : '%1 payment', $profile->getTrialTotalBillingCycles())) ?></span>
                        </dd>
                    </dl>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {
            var skipNextSubscriptionModal = $('#change-repeat-modal');

            modal({
                buttons: [],
                type: 'popup',
                responsive: true,
                innerScroll: true
            }, skipNextSubscriptionModal);

            $('#change-repeat').on('click', function () {
                skipNextSubscriptionModal.modal('openModal');
            });
        });
</script>
