<?php
/* @var $block \Eleanorsoft\AheadworksSarp\Block\Customer\Subscription\Info\Products */

// @codingStandardsIgnoreFile
?>
<?php
    $profile = $block->getProfile();
?>
<div class="block aw_sarp-customer-subscription_products">
    <div id="subscription-products_title" class="block-title">
        <strong><?php echo $block->escapeHtml(__('Products')) ?></strong>
    </div>
    <div class="block-content" id="product-table">
        <div class="table-wrapper">
            <table class="data table">
                <thead>
                    <tr>
                        <th scope="col" class="col product-name"><?php echo $block->escapeHtml(__('Product')) ?></th>
                        <th scope="col" class="col qty"><?php echo $block->escapeHtml(__('Qty')) ?></th>
                        <th scope="col" class="col regular-price"><?php echo $block->escapeHtml(__('Price')) ?></th>
                        <th scope="col" class="col initial-fee"><?php echo $block->escapeHtml(__('Total')) ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($profile->getItems() as $item): ?>
                    <?php
                        $product = $block->getProduct($item->getProductId());
                    ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Product Name')) ?>" class="col product-name">
                            <?php if ($block->isProductExists($item->getProductId()) && $block->hasProductUrl($item->getProductId())): ?>
                                <a href="<?php echo $block->escapeUrl($block->getProductUrl($item->getProductId())) ?>">
                                    <span><?php echo $block->escapeHtml($item->getName()) ?></span>
                                    <?php echo $block->getImage($product, 'cart_page_product_thumbnail')->toHtml(); ?>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($item->getName()) ?>
                            <?php endif; ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Qty')) ?>" class="col qty">
                            <?php /* @noEscape */ echo $item->getQty() ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Price')) ?>" class="col regular-price">
                            <?php /* @noEscape */ echo $product->getFinalPrice() ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Total')) ?>" class="col initial-fee">
                            <?php if ($profile->getIsInitialFeeEnabled()): ?>
                                <?php /* @noEscape */ echo $block->formatProfileItemAmount($item->getInitialFee(), $profile->getProfileCurrencyCode()) ?>
                            <?php else: ?>
                                <?php echo $block->escapeHtml(__('No')) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#product-table": {
        "esAHeadWorkSarpSubscribe":{ "productId": "<?php print 'test' ?>" }
    }
}
</script>
