<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions-toolbar subscription-toolbar">
    <div class="secondary"><a class="action back" style="text-decoration-line: none" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span class="btn-2 btn-back-subscription"><?php /* @escapeNotVerified */ echo __('Back') ?></span></a></div>
</div>
