<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount" id="block-discount" <?php /* data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}' */ ?> >
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Promo Code:') ?></strong> <span class="pull-right">Enter code at Checkout</span>
    </div>
</div>
