<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
	<div class="cart top actions">
		<?php if ($block->getContinueShoppingUrl()): ?>
			<a class="action secondary"
			   href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
			   title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
				<span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
			</a>
		<?php endif; ?>
	</div>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                    <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></th>
	                <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Total') ?></span></th>
	                <th class="col remove" scope="col"><span><?php /* @escapeNotVerified */ echo __('Remove') ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
    </div>
    <?php /* <div class="cart main actions">
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php echo __('Clear Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div> */ ?>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

<script type="text/javascript">
	// Plus-minus qty feature
	require([
			'jquery'
		],
		function($) {
			$('.qty .qty-inc').click(function() {
				var $input = $(this).parent().find('input.qty');
				var val = parseInt($input.val()) + parseInt($(this).attr('data-inc'));
				if ( !val ) val = 1;
				$input.val(val);
			});
		}
	);

</script>